import fs from 'fs'
import path from 'path'

async function populateRemainingCategories() {
  try {
    console.log('🚀 Populating remaining categories with businesses...')
    
    // Read the businesses.json file
    const businessesPath = path.join(process.cwd(), 'public', 'data', 'businesses.json')
    const businessesData = JSON.parse(fs.readFileSync(businessesPath, 'utf8'))
    
    // Define businesses for remaining categories
    const newBusinesses = [
      // BUTCHERS
      {
        name: 'Waterlooville Butchers',
        slug: 'waterlooville-butchers',
        category: 'butchers',
        area: 'waterlooville',
        postcode: 'PO10 5XX',
        address: '45 High Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1260',
        website: 'https://waterloovillebutchers.co.uk',
        description: 'Traditional family butchers offering fresh meat, poultry, and deli products. Quality cuts and friendly service.',
        rating: 4.8,
        review_count: 89,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Hampshire Meats',
        slug: 'hampshire-meats',
        category: 'butchers',
        area: 'waterlooville',
        postcode: 'PO10 6XX',
        address: '32 Market Square, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1261',
        website: 'https://hampshiremeats.co.uk',
        description: 'Premium butcher shop specializing in locally sourced meats and traditional cuts.',
        rating: 4.7,
        review_count: 56,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // BAKERIES
      {
        name: 'Waterlooville Bakery',
        slug: 'waterlooville-bakery',
        category: 'bakeries',
        area: 'waterlooville',
        postcode: 'PO10 7XX',
        address: '28 Baker Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1262',
        website: 'https://waterloovillebakery.co.uk',
        description: 'Traditional bakery offering fresh bread, cakes, pastries, and custom celebration cakes.',
        rating: 4.9,
        review_count: 124,
        images: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800'],
        featured: true
      },
      {
        name: 'Sweet Treats Bakery',
        slug: 'sweet-treats-bakery',
        category: 'bakeries',
        area: 'waterlooville',
        postcode: 'PO10 8XX',
        address: '15 Sweet Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1263',
        website: 'https://sweettreatsbakery.co.uk',
        description: 'Artisan bakery specializing in custom cakes, cupcakes, and sweet treats for all occasions.',
        rating: 4.8,
        review_count: 78,
        images: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800'],
        featured: false
      },
      
      // FLORISTS
      {
        name: 'Waterlooville Florists',
        slug: 'waterlooville-florists',
        category: 'florists',
        area: 'waterlooville',
        postcode: 'PO10 9XX',
        address: '22 Flower Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1264',
        website: 'https://waterloovilleflorists.co.uk',
        description: 'Professional florist offering fresh flowers, bouquets, and arrangements for all occasions.',
        rating: 4.8,
        review_count: 92,
        images: ['https://images.unsplash.com/photo-1563241527-3004b7be0ffd?w=800'],
        featured: true
      },
      {
        name: 'Blooms & Buds',
        slug: 'blooms-buds',
        category: 'florists',
        area: 'waterlooville',
        postcode: 'PO11 1XX',
        address: '18 Bloom Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1265',
        website: 'https://bloomsandbuds.co.uk',
        description: 'Creative florist specializing in wedding flowers, event arrangements, and seasonal displays.',
        rating: 4.7,
        review_count: 65,
        images: ['https://images.unsplash.com/photo-1563241527-3004b7be0ffd?w=800'],
        featured: false
      },
      
      // GIFT SHOPS
      {
        name: 'Waterlooville Gift Shop',
        slug: 'waterlooville-gift-shop',
        category: 'gift-shops',
        area: 'waterlooville',
        postcode: 'PO11 2XX',
        address: '35 Gift Row, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1266',
        website: 'https://waterloovillegiftshop.co.uk',
        description: 'Unique gift shop offering cards, presents, and special occasion items for all ages.',
        rating: 4.6,
        review_count: 43,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      {
        name: 'Treasure Trove',
        slug: 'treasure-trove',
        category: 'gift-shops',
        area: 'waterlooville',
        postcode: 'PO11 3XX',
        address: '12 Treasure Close, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1267',
        website: 'https://treasuretrove.co.uk',
        description: 'Curated gift shop featuring unique items, homeware, and personalized gifts.',
        rating: 4.8,
        review_count: 71,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      
      // CONVENIENCE STORES
      {
        name: 'Waterlooville Convenience Store',
        slug: 'waterlooville-convenience-store',
        category: 'convenience-stores',
        area: 'waterlooville',
        postcode: 'PO11 4XX',
        address: '42 Convenience Road, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1268',
        website: 'https://waterloovilleconvenience.co.uk',
        description: 'Local convenience store offering groceries, household items, and everyday essentials.',
        rating: 4.5,
        review_count: 38,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      {
        name: 'Quick Stop Shop',
        slug: 'quick-stop-shop',
        category: 'convenience-stores',
        area: 'waterlooville',
        postcode: 'PO11 5XX',
        address: '25 Quick Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1269',
        website: 'https://quickstopshop.co.uk',
        description: 'Family-run convenience store with friendly service and competitive prices.',
        rating: 4.7,
        review_count: 52,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      
      // BARBERS
      {
        name: 'Waterlooville Barbers',
        slug: 'waterlooville-barbers',
        category: 'barbers',
        area: 'waterlooville',
        postcode: 'PO11 6XX',
        address: '38 Barber Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1270',
        website: 'https://waterloovillebarbers.co.uk',
        description: 'Traditional barber shop offering men\'s haircuts, beard trimming, and grooming services.',
        rating: 4.8,
        review_count: 95,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Gentleman\'s Cut',
        slug: 'gentlemans-cut',
        category: 'barbers',
        area: 'waterlooville',
        postcode: 'PO11 7XX',
        address: '15 Gentleman Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1271',
        website: 'https://gentlemanscut.co.uk',
        description: 'Premium barber shop specializing in classic cuts and modern styling for men.',
        rating: 4.7,
        review_count: 67,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // BEAUTY SALONS
      {
        name: 'Waterlooville Beauty Salon',
        slug: 'waterlooville-beauty-salon',
        category: 'beauty-salons',
        area: 'waterlooville',
        postcode: 'PO11 8XX',
        address: '28 Beauty Boulevard, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1272',
        website: 'https://waterloovillebeauty.co.uk',
        description: 'Professional beauty salon offering treatments, skincare, and relaxation services.',
        rating: 4.9,
        review_count: 118,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Serenity Spa',
        slug: 'serenity-spa',
        category: 'beauty-salons',
        area: 'waterlooville',
        postcode: 'PO11 9XX',
        address: '22 Serenity Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1273',
        website: 'https://serenityspa.co.uk',
        description: 'Luxury spa offering facial treatments, massages, and wellness services.',
        rating: 4.8,
        review_count: 84,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // NAIL TECHNICIANS
      {
        name: 'Waterlooville Nail Studio',
        slug: 'waterlooville-nail-studio',
        category: 'nail-technicians',
        area: 'waterlooville',
        postcode: 'PO12 1XX',
        address: '18 Nail Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1274',
        website: 'https://waterloovillenailstudio.co.uk',
        description: 'Professional nail salon offering manicures, pedicures, and nail art services.',
        rating: 4.8,
        review_count: 76,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Polish Perfect',
        slug: 'polish-perfect',
        category: 'nail-technicians',
        area: 'waterlooville',
        postcode: 'PO12 2XX',
        address: '25 Polish Close, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1275',
        website: 'https://polishperfect.co.uk',
        description: 'Specialist nail salon offering gel nails, acrylics, and creative nail art.',
        rating: 4.7,
        review_count: 59,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // MASSAGE THERAPISTS
      {
        name: 'Waterlooville Massage Therapy',
        slug: 'waterlooville-massage-therapy',
        category: 'massage-therapists',
        area: 'waterlooville',
        postcode: 'PO12 3XX',
        address: '32 Massage Way, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1276',
        website: 'https://waterloovillemassage.co.uk',
        description: 'Professional massage therapy services including Swedish, deep tissue, and sports massage.',
        rating: 4.9,
        review_count: 103,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Relaxation Station',
        slug: 'relaxation-station',
        category: 'massage-therapists',
        area: 'waterlooville',
        postcode: 'PO12 4XX',
        address: '15 Relax Road, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1277',
        website: 'https://relaxationstation.co.uk',
        description: 'Therapeutic massage services for stress relief, pain management, and wellness.',
        rating: 4.8,
        review_count: 87,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // MOT CENTRES
      {
        name: 'Waterlooville MOT Centre',
        slug: 'waterlooville-mot-centre',
        category: 'mot-centres',
        area: 'waterlooville',
        postcode: 'PO12 5XX',
        address: '45 MOT Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1278',
        website: 'https://waterloovillemot.co.uk',
        description: 'Professional MOT testing and vehicle inspection services with competitive pricing.',
        rating: 4.7,
        review_count: 64,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Quick MOT',
        slug: 'quick-mot',
        category: 'mot-centres',
        area: 'waterlooville',
        postcode: 'PO12 6XX',
        address: '28 Quick Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1279',
        website: 'https://quickmot.co.uk',
        description: 'Fast MOT testing service with same-day appointments and repairs available.',
        rating: 4.6,
        review_count: 48,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // CAR WASH & VALETING
      {
        name: 'Waterlooville Car Wash',
        slug: 'waterlooville-car-wash',
        category: 'car-wash',
        area: 'waterlooville',
        postcode: 'PO12 7XX',
        address: '22 Wash Way, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1280',
        website: 'https://waterloovillecarwash.co.uk',
        description: 'Professional car washing, valeting, and detailing services for all vehicle types.',
        rating: 4.8,
        review_count: 91,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Shine & Polish',
        slug: 'shine-polish',
        category: 'car-wash',
        area: 'waterlooville',
        postcode: 'PO12 8XX',
        address: '18 Shine Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1281',
        website: 'https://shineandpolish.co.uk',
        description: 'Premium car valeting service offering interior and exterior cleaning packages.',
        rating: 4.7,
        review_count: 73,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // MOBILE MECHANICS
      {
        name: 'Waterlooville Mobile Mechanics',
        slug: 'waterlooville-mobile-mechanics',
        category: 'mobile-mechanics',
        area: 'waterlooville',
        postcode: 'PO12 9XX',
        address: '35 Mobile Road, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1282',
        website: 'https://waterloovillemobilemechanics.co.uk',
        description: 'Mobile car repair and maintenance services at your location. Convenient and professional.',
        rating: 4.9,
        review_count: 112,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Fix On Site',
        slug: 'fix-on-site',
        category: 'mobile-mechanics',
        area: 'waterlooville',
        postcode: 'PO13 1XX',
        address: '12 Fix Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1283',
        website: 'https://fixonsite.co.uk',
        description: 'Professional mobile mechanics providing car repairs and servicing at your home or workplace.',
        rating: 4.8,
        review_count: 89,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // TYRE SHOPS
      {
        name: 'Waterlooville Tyre Centre',
        slug: 'waterlooville-tyre-centre',
        category: 'tyre-shops',
        area: 'waterlooville',
        postcode: 'PO13 2XX',
        address: '42 Tyre Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1284',
        website: 'https://waterloovilletyrecentre.co.uk',
        description: 'Professional tyre fitting, repair, and replacement services with competitive prices.',
        rating: 4.7,
        review_count: 76,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Quick Tyres',
        slug: 'quick-tyres',
        category: 'tyre-shops',
        area: 'waterlooville',
        postcode: 'PO13 3XX',
        address: '25 Quick Tyre Road, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1285',
        website: 'https://quicktyres.co.uk',
        description: 'Fast tyre fitting service with same-day fitting and wheel alignment available.',
        rating: 4.6,
        review_count: 54,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // DRIVING INSTRUCTORS
      {
        name: 'Waterlooville Driving School',
        slug: 'waterlooville-driving-school',
        category: 'driving-instructors',
        area: 'waterlooville',
        postcode: 'PO13 4XX',
        address: '38 Instructor Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1286',
        website: 'https://waterloovilledrivingschool.co.uk',
        description: 'Professional driving instruction with experienced instructors and high pass rates.',
        rating: 4.8,
        review_count: 95,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Pass First Time',
        slug: 'pass-first-time',
        category: 'driving-instructors',
        area: 'waterlooville',
        postcode: 'PO13 5XX',
        address: '15 Pass Road, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1287',
        website: 'https://passfirsttime.co.uk',
        description: 'Expert driving lessons with patient instructors and flexible scheduling.',
        rating: 4.7,
        review_count: 68,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // TAKEAWAYS
      {
        name: 'Waterlooville Takeaway',
        slug: 'waterlooville-takeaway',
        category: 'takeaways',
        area: 'waterlooville',
        postcode: 'PO13 6XX',
        address: '28 Takeaway Terrace, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1288',
        website: 'https://waterloovilletakeaway.co.uk',
        description: 'Popular takeaway offering a variety of cuisines with fast delivery and collection service.',
        rating: 4.6,
        review_count: 82,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Quick Bites',
        slug: 'quick-bites',
        category: 'takeaways',
        area: 'waterlooville',
        postcode: 'PO13 7XX',
        address: '22 Quick Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1289',
        website: 'https://quickbites.co.uk',
        description: 'Fast takeaway service offering burgers, kebabs, and international cuisine.',
        rating: 4.5,
        review_count: 67,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // FISH & CHIPS SHOPS
      {
        name: 'Waterlooville Fish & Chips',
        slug: 'waterlooville-fish-chips',
        category: 'fish-chips',
        area: 'waterlooville',
        postcode: 'PO13 8XX',
        address: '35 Fish Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1290',
        website: 'https://waterloovillefishandchips.co.uk',
        description: 'Traditional fish and chip shop serving fresh fish, chips, and classic British takeaway.',
        rating: 4.8,
        review_count: 124,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Golden Fry',
        slug: 'golden-fry',
        category: 'fish-chips',
        area: 'waterlooville',
        postcode: 'PO13 9XX',
        address: '18 Golden Road, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1291',
        website: 'https://goldenfry.co.uk',
        description: 'Family-run fish and chip shop with traditional recipes and friendly service.',
        rating: 4.7,
        review_count: 89,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // CATERING SERVICES
      {
        name: 'Waterlooville Catering',
        slug: 'waterlooville-catering',
        category: 'catering-services',
        area: 'waterlooville',
        postcode: 'PO14 1XX',
        address: '42 Catering Close, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1292',
        website: 'https://waterloovillecatering.co.uk',
        description: 'Professional catering services for events, parties, and corporate functions.',
        rating: 4.8,
        review_count: 76,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Event Eats',
        slug: 'event-eats',
        category: 'catering-services',
        area: 'waterlooville',
        postcode: 'PO14 2XX',
        address: '25 Event Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1293',
        website: 'https://eventeats.co.uk',
        description: 'Specialist event catering with custom menus and professional service.',
        rating: 4.7,
        review_count: 63,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // COFFEE SHOPS
      {
        name: 'Waterlooville Coffee House',
        slug: 'waterlooville-coffee-house',
        category: 'coffee-shops',
        area: 'waterlooville',
        postcode: 'PO14 3XX',
        address: '32 Coffee Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1294',
        website: 'https://waterloovillecoffeehouse.co.uk',
        description: 'Specialty coffee shop offering artisan coffee, pastries, and light meals.',
        rating: 4.9,
        review_count: 108,
        images: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800'],
        featured: true
      },
      {
        name: 'Bean There',
        slug: 'bean-there',
        category: 'coffee-shops',
        area: 'waterlooville',
        postcode: 'PO14 4XX',
        address: '15 Bean Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1295',
        website: 'https://beanthere.co.uk',
        description: 'Independent coffee shop with locally roasted beans and homemade treats.',
        rating: 4.8,
        review_count: 84,
        images: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800'],
        featured: false
      },
      
      // NURSERIES
      {
        name: 'Waterlooville Nursery',
        slug: 'waterlooville-nursery',
        category: 'nurseries',
        area: 'waterlooville',
        postcode: 'PO14 5XX',
        address: '28 Nursery Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1296',
        website: 'https://waterloovillenursery.co.uk',
        description: 'Early years nursery providing quality childcare and education for children aged 0-5.',
        rating: 4.8,
        review_count: 92,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Little Learners',
        slug: 'little-learners',
        category: 'nurseries',
        area: 'waterlooville',
        postcode: 'PO14 6XX',
        address: '22 Learning Close, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1297',
        website: 'https://littlelearners.co.uk',
        description: 'Nurturing nursery environment with experienced staff and educational activities.',
        rating: 4.7,
        review_count: 71,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // TUTORS
      {
        name: 'Waterlooville Tutoring',
        slug: 'waterlooville-tutoring',
        category: 'tutors',
        area: 'waterlooville',
        postcode: 'PO14 7XX',
        address: '18 Tutor Terrace, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1298',
        website: 'https://waterloovilletutoring.co.uk',
        description: 'Professional tutoring services for all subjects and age groups with qualified teachers.',
        rating: 4.9,
        review_count: 115,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Study Success',
        slug: 'study-success',
        category: 'tutors',
        area: 'waterlooville',
        postcode: 'PO14 8XX',
        address: '25 Study Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1299',
        website: 'https://studysuccess.co.uk',
        description: 'Expert tutoring in maths, English, and sciences with proven results.',
        rating: 4.8,
        review_count: 87,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // DRIVING SCHOOLS
      {
        name: 'Waterlooville Driving Academy',
        slug: 'waterlooville-driving-academy',
        category: 'driving-schools',
        area: 'waterlooville',
        postcode: 'PO14 9XX',
        address: '35 Academy Road, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1300',
        website: 'https://waterloovilledrivingacademy.co.uk',
        description: 'Professional driving school with experienced instructors and high pass rates.',
        rating: 4.8,
        review_count: 96,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Safe Drive School',
        slug: 'safe-drive-school',
        category: 'driving-schools',
        area: 'waterlooville',
        postcode: 'PO15 1XX',
        address: '12 Safe Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1301',
        website: 'https://safedriveschool.co.uk',
        description: 'Comprehensive driving lessons with patient instructors and flexible scheduling.',
        rating: 4.7,
        review_count: 73,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // CHILDMINDERS
      {
        name: 'Waterlooville Childminders',
        slug: 'waterlooville-childminders',
        category: 'childminders',
        area: 'waterlooville',
        postcode: 'PO15 2XX',
        address: '28 Childcare Close, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1302',
        website: 'https://waterloovillechildminders.co.uk',
        description: 'Registered childminders providing quality childcare in a home environment.',
        rating: 4.8,
        review_count: 89,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Little Angels Childcare',
        slug: 'little-angels-childcare',
        category: 'childminders',
        area: 'waterlooville',
        postcode: 'PO15 3XX',
        address: '22 Angels Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1303',
        website: 'https://littleangelschildcare.co.uk',
        description: 'Experienced childminders offering flexible childcare with educational activities.',
        rating: 4.7,
        review_count: 65,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // PERSONAL TRAINERS
      {
        name: 'Waterlooville Personal Training',
        slug: 'waterlooville-personal-training',
        category: 'personal-trainers',
        area: 'waterlooville',
        postcode: 'PO15 4XX',
        address: '18 Training Terrace, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1304',
        website: 'https://waterloovillepersonaltraining.co.uk',
        description: 'Certified personal trainers offering one-to-one and group fitness sessions.',
        rating: 4.9,
        review_count: 127,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Fit For Life',
        slug: 'fit-for-life',
        category: 'personal-trainers',
        area: 'waterlooville',
        postcode: 'PO15 5XX',
        address: '25 Fit Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1305',
        website: 'https://fitforlife.co.uk',
        description: 'Professional personal training with customized workout plans and nutrition advice.',
        rating: 4.8,
        review_count: 94,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // YOGA & PILATES STUDIOS
      {
        name: 'Waterlooville Yoga Studio',
        slug: 'waterlooville-yoga-studio',
        category: 'yoga-studios',
        area: 'waterlooville',
        postcode: 'PO15 6XX',
        address: '32 Yoga Way, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1306',
        website: 'https://waterloovilleyogastudio.co.uk',
        description: 'Professional yoga and Pilates classes for all levels in a peaceful studio environment.',
        rating: 4.8,
        review_count: 98,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Zen Space',
        slug: 'zen-space',
        category: 'yoga-studios',
        area: 'waterlooville',
        postcode: 'PO15 7XX',
        address: '15 Zen Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1307',
        website: 'https://zenspace.co.uk',
        description: 'Mindfulness and yoga classes promoting wellness and inner peace.',
        rating: 4.7,
        review_count: 76,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // PHYSIOTHERAPISTS
      {
        name: 'Waterlooville Physiotherapy',
        slug: 'waterlooville-physiotherapy',
        category: 'physiotherapists',
        area: 'waterlooville',
        postcode: 'PO15 8XX',
        address: '42 Physio Place, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1308',
        website: 'https://waterloovillephysiotherapy.co.uk',
        description: 'Professional physiotherapy services for injury rehabilitation and pain management.',
        rating: 4.9,
        review_count: 112,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Recovery Plus',
        slug: 'recovery-plus',
        category: 'physiotherapists',
        area: 'waterlooville',
        postcode: 'PO15 9XX',
        address: '28 Recovery Road, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1309',
        website: 'https://recoveryplus.co.uk',
        description: 'Expert physiotherapy with modern equipment and personalized treatment plans.',
        rating: 4.8,
        review_count: 85,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // CHIROPRACTORS
      {
        name: 'Waterlooville Chiropractic',
        slug: 'waterlooville-chiropractic',
        category: 'chiropractors',
        area: 'waterlooville',
        postcode: 'PO16 1XX',
        address: '25 Chiro Close, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1310',
        website: 'https://waterloovillechiropractic.co.uk',
        description: 'Professional chiropractic care for spinal health and pain relief.',
        rating: 4.8,
        review_count: 91,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Spinal Care Centre',
        slug: 'spinal-care-centre',
        category: 'chiropractors',
        area: 'waterlooville',
        postcode: 'PO16 2XX',
        address: '18 Spinal Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1311',
        website: 'https://spinalcarecentre.co.uk',
        description: 'Expert chiropractic treatment for back pain, neck pain, and musculoskeletal issues.',
        rating: 4.7,
        review_count: 68,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // LETTING AGENTS
      {
        name: 'Waterlooville Letting Agents',
        slug: 'waterlooville-letting-agents',
        category: 'letting-agents',
        area: 'waterlooville',
        postcode: 'PO16 3XX',
        address: '35 Letting Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1312',
        website: 'https://waterloovillelettingagents.co.uk',
        description: 'Professional letting agents specializing in property rental and management services.',
        rating: 4.8,
        review_count: 87,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Rent Right',
        slug: 'rent-right',
        category: 'letting-agents',
        area: 'waterlooville',
        postcode: 'PO16 4XX',
        address: '22 Rent Road, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1313',
        website: 'https://rentright.co.uk',
        description: 'Experienced letting agents with comprehensive property management services.',
        rating: 4.7,
        review_count: 74,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // REMOVAL COMPANIES
      {
        name: 'Waterlooville Removals',
        slug: 'waterlooville-removals',
        category: 'removal-companies',
        area: 'waterlooville',
        postcode: 'PO16 5XX',
        address: '42 Removal Way, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1314',
        website: 'https://waterloovilleremovals.co.uk',
        description: 'Professional removal company offering house moves and relocation services.',
        rating: 4.8,
        review_count: 96,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Move Easy',
        slug: 'move-easy',
        category: 'removal-companies',
        area: 'waterlooville',
        postcode: 'PO16 6XX',
        address: '28 Move Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1315',
        website: 'https://moveeasy.co.uk',
        description: 'Reliable removal services with experienced team and competitive pricing.',
        rating: 4.7,
        review_count: 82,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // BOOKKEEPERS
      {
        name: 'Waterlooville Bookkeeping',
        slug: 'waterlooville-bookkeeping',
        category: 'bookkeepers',
        area: 'waterlooville',
        postcode: 'PO16 7XX',
        address: '18 Book Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1316',
        website: 'https://waterloovillebookkeeping.co.uk',
        description: 'Professional bookkeeping services for small businesses and self-employed individuals.',
        rating: 4.8,
        review_count: 73,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Numbers Right',
        slug: 'numbers-right',
        category: 'bookkeepers',
        area: 'waterlooville',
        postcode: 'PO16 8XX',
        address: '25 Numbers Close, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1317',
        website: 'https://numbersright.co.uk',
        description: 'Expert bookkeeping with cloud-based systems and regular reporting.',
        rating: 4.7,
        review_count: 59,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // IT SERVICES
      {
        name: 'Waterlooville IT Services',
        slug: 'waterlooville-it-services',
        category: 'it-services',
        area: 'waterlooville',
        postcode: 'PO16 9XX',
        address: '32 IT Way, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1318',
        website: 'https://waterloovilleitservices.co.uk',
        description: 'Professional IT support, computer repairs, and technology consulting services.',
        rating: 4.8,
        review_count: 89,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Tech Solutions',
        slug: 'tech-solutions',
        category: 'it-services',
        area: 'waterlooville',
        postcode: 'PO17 1XX',
        address: '15 Tech Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1319',
        website: 'https://techsolutions.co.uk',
        description: 'Expert IT support for businesses and individuals with fast response times.',
        rating: 4.7,
        review_count: 76,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // WEB DESIGNERS
      {
        name: 'Waterlooville Web Design',
        slug: 'waterlooville-web-design',
        category: 'web-designers',
        area: 'waterlooville',
        postcode: 'PO17 2XX',
        address: '42 Web Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1320',
        website: 'https://waterloovillewebdesign.co.uk',
        description: 'Professional web design and development services for businesses and individuals.',
        rating: 4.9,
        review_count: 105,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Digital Creative',
        slug: 'digital-creative',
        category: 'web-designers',
        area: 'waterlooville',
        postcode: 'PO17 3XX',
        address: '28 Digital Road, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1321',
        website: 'https://digitalcreative.co.uk',
        description: 'Creative web design agency specializing in modern, responsive websites.',
        rating: 4.8,
        review_count: 87,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // MARKETING AGENCIES
      {
        name: 'Waterlooville Marketing',
        slug: 'waterlooville-marketing',
        category: 'marketing-agencies',
        area: 'waterlooville',
        postcode: 'PO17 4XX',
        address: '25 Marketing Close, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1322',
        website: 'https://waterloovillemarketing.co.uk',
        description: 'Digital marketing agency offering SEO, social media, and advertising services.',
        rating: 4.8,
        review_count: 92,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Grow Digital',
        slug: 'grow-digital',
        category: 'marketing-agencies',
        area: 'waterlooville',
        postcode: 'PO17 5XX',
        address: '18 Grow Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1323',
        website: 'https://growdigital.co.uk',
        description: 'Results-driven marketing agency helping businesses grow online.',
        rating: 4.7,
        review_count: 78,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // PRINTERS
      {
        name: 'Waterlooville Printers',
        slug: 'waterlooville-printers',
        category: 'printers',
        area: 'waterlooville',
        postcode: 'PO17 6XX',
        address: '35 Print Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1324',
        website: 'https://waterloovilleprinters.co.uk',
        description: 'Professional printing services for business cards, flyers, and promotional materials.',
        rating: 4.7,
        review_count: 64,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Print Perfect',
        slug: 'print-perfect',
        category: 'printers',
        area: 'waterlooville',
        postcode: 'PO17 7XX',
        address: '22 Perfect Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1325',
        website: 'https://printperfect.co.uk',
        description: 'Quality printing services with fast turnaround and competitive pricing.',
        rating: 4.6,
        review_count: 51,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // PHOTOGRAPHERS
      {
        name: 'Waterlooville Photography',
        slug: 'waterlooville-photography',
        category: 'photographers',
        area: 'waterlooville',
        postcode: 'PO17 8XX',
        address: '18 Photo Close, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1326',
        website: 'https://waterloovillephotography.co.uk',
        description: 'Professional photography services for weddings, portraits, and events.',
        rating: 4.9,
        review_count: 118,
        images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800'],
        featured: true
      },
      {
        name: 'Capture Moments',
        slug: 'capture-moments',
        category: 'photographers',
        area: 'waterlooville',
        postcode: 'PO17 9XX',
        address: '25 Capture Road, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1327',
        website: 'https://capturemoments.co.uk',
        description: 'Creative photographer specializing in family portraits and special occasions.',
        rating: 4.8,
        review_count: 94,
        images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800'],
        featured: false
      },
      
      // GRAPHIC DESIGNERS
      {
        name: 'Waterlooville Graphic Design',
        slug: 'waterlooville-graphic-design',
        category: 'graphic-designers',
        area: 'waterlooville',
        postcode: 'PO18 1XX',
        address: '32 Design Way, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1328',
        website: 'https://waterloovillegraphicdesign.co.uk',
        description: 'Professional graphic design services for logos, branding, and marketing materials.',
        rating: 4.8,
        review_count: 86,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Creative Studio',
        slug: 'creative-studio',
        category: 'graphic-designers',
        area: 'waterlooville',
        postcode: 'PO18 2XX',
        address: '15 Creative Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1329',
        website: 'https://creativestudio.co.uk',
        description: 'Innovative graphic design studio creating memorable visual identities.',
        rating: 4.7,
        review_count: 72,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // WEDDING PLANNERS
      {
        name: 'Waterlooville Wedding Planners',
        slug: 'waterlooville-wedding-planners',
        category: 'wedding-planners',
        area: 'waterlooville',
        postcode: 'PO18 3XX',
        address: '42 Wedding Way, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1330',
        website: 'https://waterloovilleweddingplanners.co.uk',
        description: 'Professional wedding planning services creating perfect days for couples.',
        rating: 4.9,
        review_count: 127,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Perfect Day Events',
        slug: 'perfect-day-events',
        category: 'wedding-planners',
        area: 'waterlooville',
        postcode: 'PO18 4XX',
        address: '28 Perfect Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1331',
        website: 'https://perfectdayevents.co.uk',
        description: 'Experienced wedding planners ensuring every detail is perfect for your special day.',
        rating: 4.8,
        review_count: 103,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // DJS
      {
        name: 'Waterlooville DJ Services',
        slug: 'waterlooville-dj-services',
        category: 'djs',
        area: 'waterlooville',
        postcode: 'PO18 5XX',
        address: '25 DJ Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1332',
        website: 'https://waterloovilledjservices.co.uk',
        description: 'Professional DJ services for weddings, parties, and events with quality sound equipment.',
        rating: 4.8,
        review_count: 95,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Sound Wave DJs',
        slug: 'sound-wave-djs',
        category: 'djs',
        area: 'waterlooville',
        postcode: 'PO18 6XX',
        address: '18 Sound Close, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1333',
        website: 'https://soundwavedjs.co.uk',
        description: 'Experienced DJs providing entertainment for all occasions with extensive music library.',
        rating: 4.7,
        review_count: 81,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // TAXI FIRMS
      {
        name: 'Waterlooville Taxis',
        slug: 'waterlooville-taxis',
        category: 'taxi-firms',
        area: 'waterlooville',
        postcode: 'PO18 7XX',
        address: '35 Taxi Terrace, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1334',
        website: 'https://waterloovilletaxis.co.uk',
        description: 'Reliable taxi service with professional drivers and competitive rates.',
        rating: 4.7,
        review_count: 89,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Quick Cabs',
        slug: 'quick-cabs',
        category: 'taxi-firms',
        area: 'waterlooville',
        postcode: 'PO18 8XX',
        address: '22 Quick Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1335',
        website: 'https://quickcabs.co.uk',
        description: 'Fast taxi service with modern vehicles and friendly drivers.',
        rating: 4.6,
        review_count: 67,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // COMMUNITY CENTRES
      {
        name: 'Waterlooville Community Centre',
        slug: 'waterlooville-community-centre',
        category: 'community-centres',
        area: 'waterlooville',
        postcode: 'PO18 9XX',
        address: '42 Community Way, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1336',
        website: 'https://waterloovillecommunitycentre.co.uk',
        description: 'Vibrant community center offering activities, events, and meeting spaces for all ages.',
        rating: 4.8,
        review_count: 76,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Unity Hall',
        slug: 'unity-hall',
        category: 'community-centres',
        area: 'waterlooville',
        postcode: 'PO19 1XX',
        address: '28 Unity Street, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1337',
        website: 'https://unityhall.co.uk',
        description: 'Community hall hosting events, classes, and social activities for the local community.',
        rating: 4.7,
        review_count: 63,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      },
      
      // CHARITIES
      {
        name: 'Waterlooville Community Charity',
        slug: 'waterlooville-community-charity',
        category: 'charities',
        area: 'waterlooville',
        postcode: 'PO19 2XX',
        address: '15 Charity Close, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1338',
        website: 'https://waterloovillecommunitycharity.co.uk',
        description: 'Local charity supporting community projects and helping those in need.',
        rating: 4.9,
        review_count: 142,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: true
      },
      {
        name: 'Helping Hands',
        slug: 'helping-hands',
        category: 'charities',
        area: 'waterlooville',
        postcode: 'PO19 3XX',
        address: '25 Helping Lane, Waterlooville',
        lat: 50.8847,
        lng: -1.0304,
        phone: '023 9200 1339',
        website: 'https://helpinghands.co.uk',
        description: 'Volunteer charity providing support and assistance to vulnerable members of the community.',
        rating: 4.8,
        review_count: 98,
        images: ['https://images.unsplash.com/photo-1581578731548-c6d0f3e0c4e8?w=800'],
        featured: false
      }
    ]
    
    // Add timestamps to new businesses
    const timestampedBusinesses = newBusinesses.map(business => ({
      ...business,
      id: `new-${business.slug}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    }))
    
    // Add new businesses to existing data
    const updatedBusinesses = [...businessesData, ...timestampedBusinesses]
    
    // Write updated data back
    fs.writeFileSync(businessesPath, JSON.stringify(updatedBusinesses, null, 2))
    
    console.log(`\n🎉 Successfully added ${timestampedBusinesses.length} businesses to remaining categories!`)
    console.log(`📊 Summary:`)
    console.log(`  - Businesses added: ${timestampedBusinesses.length}`)
    console.log(`  - Total businesses: ${businessesData.length} -> ${updatedBusinesses.length}`)
    console.log(`  - Categories populated: ${new Set(timestampedBusinesses.map(b => b.category)).size}`)
    console.log(`📁 Updated: ${businessesPath}`)
    
  } catch (error) {
    console.error('❌ Error adding businesses:', error)
  }
}

populateRemainingCategories()

